FROM python:3.10-slim

RUN apt-get update && apt-get install -y \
    build-essential \
    libpcap-dev \
    iproute2 \
    telnet \
    && rm -rf /var/lib/apt/lists/*

RUN python3 -m venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"

COPY . /opt/sniffer

WORKDIR /opt/sniffer

RUN pip install --no-cache-dir --upgrade pip
RUN pip install --no-cache-dir .

CMD ["iproto-sniffer", "--interface", "eth0", "--hex", "--show_headers", "--output", "sniffered.txt"]
